### ISSUE TITLE
Async crawler

### ISSUE THREAD

**Issue by alex4o** [FortyIX/Keats-Crawler#5]
Can you make the crawler async, as it will help with the development of the ui.

**Comment by FortyIX** [comment]
Working on it

**Comment by FortyIX** [comment]
I got an error, and where is self.crawl initially defined ?

```python

 Traceback (most recent call last):
   File "/Users/fuzhang/Desktop/pyProject/Keats-Crawler/src/gui/__init__.py", line 28, in <module>
     KeatsApp().run()
   File "/Users/fuzhang/Library/Python/3.6/lib/python/site-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "/Users/fuzhang/Desktop/pyProject/Keats-Crawler/src/gui/__init__.py", line 16, in build
     login.set_crawl(self.crawl)
 AttributeError: 'KeatsApp' object has no attribute 'crawl'


```

**Comment by alex4o** [comment]
It passes the data fro
```python
app = KeatsApp()
        app.set_crawl(spider)
        app.run()
```
to
```python
def set_crawl(self, crawl):
        self.crawl = crawl
```

**Comment by FortyIX** [comment]
okay i see
